name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-15:
    runs-on: macos-15
    steps:
      - name: Install FPC
        run: |
          brew update
          brew install fpc
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile SDL3 unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3.pas
          verbosity: ewnh
      - name: Compile SDL3_image unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_image.pas
          verbosity: ewnh
      - name: Compile SDL3_ttf unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_ttf.pas
          verbosity: ewnh
      - name: Compile SDL3_textengine unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_textengine.pas
          verbosity: ewnh

  # This job runs inside a Fedora Rawhide container instead of straight
  # on the Ubuntu runner, because (at the moment of writing this comment)
  # the latest Ubuntu version supported by GitHub Actions is 24.04, which
  # does not have an SDL3 package.
  fedora-rawhide:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:rawhide
    steps:
      - name: Install FPC
        run: |
           dnf install --assumeyes --setopt=install_weak_deps=False diffutils gcc fpc SDL3-devel
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile SDL3 unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3.pas
          verbosity: ewnh
      - name: Compile SDL3_image unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_image.pas
          verbosity: ewnh
      - name: Compile SDL3_ttf unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_ttf.pas
          verbosity: ewnh
      - name: Compile SDL3_textengine unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_textengine.pas
          verbosity: ewnh
      - name: Run type-sizes test
        run: ./tests/type-sizes.sh

  windows-2025:
    runs-on: windows-2025
    steps:
      - name: Install Lazarus
        run: |
          choco install lazarus
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile SDL3 unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3.pas
          verbosity: ewnh
      - name: Compile SDL3_image unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_image.pas
          verbosity: ewnh
      - name: Compile SDL3_ttf unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_ttf.pas
          verbosity: ewnh
      - name: Compile SDL3_textengine unit
        uses: suve/GHActions-FPC@v0.4.0
        with:
          source: units/SDL3_textengine.pas
          verbosity: ewnh
